### ISSUE TITLE
armv7-linux-androideabi build fails

### ISSUE THREAD

**Issue by Da-Miao** [0xor0ne/debugoff#2]
cargo build --target armv7-linux-androideabi --release

 Compiling debugoff v0.2.1

error: cannot use register `r7`: the frame pointer (r7) cannot be used as an operand for inline asm
  --> C:\Users\DaMiao\.cargo\registry\src\github.com-1ecc6299db9ec823\debugoff-0.2.1\src\arch\arm\syscall.rs:80:9
   |
80 |         in("r7") n as usize,
   |         ^^^^^^^^^^^^^^^^^^^

error: cannot use register `r7`: the frame pointer (r7) cannot be used as an operand for inline asm
   --> C:\Users\DaMiao\.cargo\registry\src\github.com-1ecc6299db9ec823\debugoff-0.2.1\src\arch\arm\syscall.rs: 100:9
    |
100 |         in("r7") n as usize,
    |         ^^^^^^^^^^^^^^^^^^^

error: could not compile `debugoff` due to 2 previous errors

**Comment by 0xor0ne** [comment]
This is due to the fact that `r7` in ARM is an LLVM-reserved register and `rustc` currently disallows using these registers in `asm!` (see https://github.com/rust-lang/rust/issues/85056).

I fixed this in `debugoff` v0.2.2 (https://github.com/0xor0ne/debugoff/commit/d5c38bd2ee30615e04ea9cc33636f0bf619a776f) by using `r8` as input register and then copy its content in `r7` before the actual syscall.

Once the reserved registers issue in `rustc` will be solved I will fix this issue in a better way.
